import { TRAINING_TRANSLATIONS } from "./training-translations";

export type UserRole = "super_admin" | "admin" | "lender" | "regulator" | "viewer";

export interface TrainingQuestion {
  id: string;
  question: string;
  correct: boolean;
  explanation: string;
}

export interface TrainingModule {
  id: string;
  title: string;
  description: string;
  icon: string;
  color: string;
  estimatedMinutes: number;
  passPercent: number;
  questions: TrainingQuestion[];
  roles: UserRole[];
}

const MODULE_META = [
  {
    id: "platform-overview",
    tKey: "platformOverview" as const,
    icon: "Monitor",
    color: "from-blue-500 to-blue-600",
    estimatedMinutes: 8,
    passPercent: 70,
    roles: ["super_admin", "admin", "lender", "regulator", "viewer"] as UserRole[],
    questions: [
      { id: "po-1", qk: "q1q" as const, ek: "q1e" as const, correct: true },
      { id: "po-2", qk: "q2q" as const, ek: "q2e" as const, correct: false },
      { id: "po-3", qk: "q3q" as const, ek: "q3e" as const, correct: true },
      { id: "po-4", qk: "q4q" as const, ek: "q4e" as const, correct: false },
      { id: "po-5", qk: "q5q" as const, ek: "q5e" as const, correct: true },
      { id: "po-6", qk: "q6q" as const, ek: "q6e" as const, correct: false },
      { id: "po-7", qk: "q7q" as const, ek: "q7e" as const, correct: true },
      { id: "po-8", qk: "q8q" as const, ek: "q8e" as const, correct: false },
    ],
  },
  {
    id: "borrower-management",
    tKey: "borrowerManagement" as const,
    icon: "Users",
    color: "from-teal-500 to-teal-600",
    estimatedMinutes: 10,
    passPercent: 70,
    roles: ["super_admin", "admin", "lender", "viewer"] as UserRole[],
    questions: [
      { id: "bm-1", qk: "q1q" as const, ek: "q1e" as const, correct: false },
      { id: "bm-2", qk: "q2q" as const, ek: "q2e" as const, correct: true },
      { id: "bm-3", qk: "q3q" as const, ek: "q3e" as const, correct: true },
      { id: "bm-4", qk: "q4q" as const, ek: "q4e" as const, correct: false },
      { id: "bm-5", qk: "q5q" as const, ek: "q5e" as const, correct: true },
      { id: "bm-6", qk: "q6q" as const, ek: "q6e" as const, correct: true },
      { id: "bm-7", qk: "q7q" as const, ek: "q7e" as const, correct: false },
      { id: "bm-8", qk: "q8q" as const, ek: "q8e" as const, correct: true },
    ],
  },
  {
    id: "credit-accounts-scoring",
    tKey: "creditAccountsScoring" as const,
    icon: "CreditCard",
    color: "from-purple-500 to-purple-600",
    estimatedMinutes: 10,
    passPercent: 70,
    roles: ["super_admin", "admin", "lender"] as UserRole[],
    questions: [
      { id: "cs-1", qk: "q1q" as const, ek: "q1e" as const, correct: true },
      { id: "cs-2", qk: "q2q" as const, ek: "q2e" as const, correct: false },
      { id: "cs-3", qk: "q3q" as const, ek: "q3e" as const, correct: true },
      { id: "cs-4", qk: "q4q" as const, ek: "q4e" as const, correct: true },
      { id: "cs-5", qk: "q5q" as const, ek: "q5e" as const, correct: false },
      { id: "cs-6", qk: "q6q" as const, ek: "q6e" as const, correct: false },
      { id: "cs-7", qk: "q7q" as const, ek: "q7e" as const, correct: true },
      { id: "cs-8", qk: "q8q" as const, ek: "q8e" as const, correct: true },
    ],
  },
  {
    id: "disputes-compliance",
    tKey: "disputesCompliance" as const,
    icon: "Shield",
    color: "from-amber-500 to-amber-600",
    estimatedMinutes: 10,
    passPercent: 70,
    roles: ["super_admin", "admin", "lender", "regulator"] as UserRole[],
    questions: [
      { id: "dc-1", qk: "q1q" as const, ek: "q1e" as const, correct: true },
      { id: "dc-2", qk: "q2q" as const, ek: "q2e" as const, correct: false },
      { id: "dc-3", qk: "q3q" as const, ek: "q3e" as const, correct: true },
      { id: "dc-4", qk: "q4q" as const, ek: "q4e" as const, correct: true },
      { id: "dc-5", qk: "q5q" as const, ek: "q5e" as const, correct: false },
      { id: "dc-6", qk: "q6q" as const, ek: "q6e" as const, correct: true },
      { id: "dc-7", qk: "q7q" as const, ek: "q7e" as const, correct: false },
      { id: "dc-8", qk: "q8q" as const, ek: "q8e" as const, correct: true },
    ],
  },
  {
    id: "ai-cross-border",
    tKey: "aiCrossBorder" as const,
    icon: "Brain",
    color: "from-violet-500 to-violet-600",
    estimatedMinutes: 8,
    passPercent: 70,
    roles: ["super_admin", "admin", "lender", "regulator"] as UserRole[],
    questions: [
      { id: "ai-1", qk: "q1q" as const, ek: "q1e" as const, correct: true },
      { id: "ai-2", qk: "q2q" as const, ek: "q2e" as const, correct: false },
      { id: "ai-3", qk: "q3q" as const, ek: "q3e" as const, correct: true },
      { id: "ai-4", qk: "q4q" as const, ek: "q4e" as const, correct: false },
      { id: "ai-5", qk: "q5q" as const, ek: "q5e" as const, correct: true },
      { id: "ai-6", qk: "q6q" as const, ek: "q6e" as const, correct: true },
      { id: "ai-7", qk: "q7q" as const, ek: "q7e" as const, correct: false },
      { id: "ai-8", qk: "q8q" as const, ek: "q8e" as const, correct: true },
    ],
  },
  {
    id: "administration-roles",
    tKey: "administrationRoles" as const,
    icon: "Settings",
    color: "from-rose-500 to-rose-600",
    estimatedMinutes: 8,
    passPercent: 70,
    roles: ["super_admin", "admin"] as UserRole[],
    questions: [
      { id: "ar-1", qk: "q1q" as const, ek: "q1e" as const, correct: false },
      { id: "ar-2", qk: "q2q" as const, ek: "q2e" as const, correct: true },
      { id: "ar-3", qk: "q3q" as const, ek: "q3e" as const, correct: false },
      { id: "ar-4", qk: "q4q" as const, ek: "q4e" as const, correct: false },
      { id: "ar-5", qk: "q5q" as const, ek: "q5e" as const, correct: true },
      { id: "ar-6", qk: "q6q" as const, ek: "q6e" as const, correct: true },
      { id: "ar-7", qk: "q7q" as const, ek: "q7e" as const, correct: true },
      { id: "ar-8", qk: "q8q" as const, ek: "q8e" as const, correct: false },
    ],
  },
];

const HARDCODED_MODULES: TrainingModule[] = [
  {
    id: "system-configuration",
    title: "System Configuration & APIs",
    description: "API key management, webhook setup, exchange rate overrides, audit logs, multi-tenant isolation, and the Command Center.",
    icon: "Terminal",
    color: "from-cyan-500 to-cyan-600",
    estimatedMinutes: 10,
    passPercent: 70,
    roles: ["super_admin"],
    questions: [
      {
        id: "sc-1",
        question: "API keys for each institution can be generated and managed from the API Configuration page.",
        correct: true,
        explanation: "Correct. The API Configuration page allows Super Admins to create, rotate, and revoke API keys per institution with configurable scopes and rate limits.",
      },
      {
        id: "sc-2",
        question: "Webhook endpoints can use plain HTTP without any encryption.",
        correct: false,
        explanation: "Webhook endpoints must use HTTPS. Plain HTTP endpoints are rejected to ensure event payloads are encrypted in transit and cannot be intercepted.",
      },
      {
        id: "sc-3",
        question: "The platform can automatically sync exchange rates every 6 hours from a configured provider.",
        correct: true,
        explanation: "Correct. Auto-sync is configurable per currency. Super Admins can also override any rate manually from the Exchange Rates page when needed.",
      },
      {
        id: "sc-4",
        question: "Audit log entries can be permanently deleted by a Super Admin to free up storage space.",
        correct: false,
        explanation: "Audit logs are immutable — no user, including Super Admins, can delete them. This ensures a tamper-proof regulatory trail for all system actions.",
      },
      {
        id: "sc-5",
        question: "Multi-tenant isolation means each institution can only see borrower records that belong to their own institution.",
        correct: true,
        explanation: "Correct. Tenant isolation is enforced at the database query level. Cross-institution data access requires explicit Super Admin grants or regulatory permissions.",
      },
      {
        id: "sc-6",
        question: "The Command Center is accessible to all logged-in users including Lenders and Viewers.",
        correct: false,
        explanation: "The Command Center is restricted to Super Admin only. It provides multi-country oversight, platform health metrics, billing controls, and system-wide configuration.",
      },
      {
        id: "sc-7",
        question: "A Super Admin can manually override a currency exchange rate when the auto-synced rate is incorrect.",
        correct: true,
        explanation: "Correct. Manual overrides are logged in the audit trail with a reason code and the approving Super Admin's identity for full traceability.",
      },
      {
        id: "sc-8",
        question: "Failed webhook deliveries are automatically retried with increasing delays between attempts.",
        correct: true,
        explanation: "Correct. The system uses exponential backoff for webhook retries. Failed deliveries are visible in the Webhook Management page with full delivery logs.",
      },
    ],
  },
  {
    id: "regulatory-oversight",
    title: "Regulatory Oversight & Reporting",
    description: "Regulatory dashboard, BoG and BSL export formats, compliance queue, cross-border agreements, and regulator permissions.",
    icon: "Landmark",
    color: "from-emerald-600 to-green-700",
    estimatedMinutes: 10,
    passPercent: 70,
    roles: ["super_admin", "admin", "regulator"],
    questions: [
      {
        id: "ro-1",
        question: "The Regulatory Dashboard shows NPL ratios, submission rates, and consent coverage across all institutions.",
        correct: true,
        explanation: "Correct. The Regulatory Dashboard provides a real-time view of portfolio health including NPL ratios, SLA compliance, data submission rates, and borrower consent coverage.",
      },
      {
        id: "ro-2",
        question: "The BoG export file format complies with Bank of Ghana CRB v1.1 regulations.",
        correct: true,
        explanation: "Correct. The BoG export generates structured files in the exact format required by the Bank of Ghana Credit Reporting Bureau v1.1 specification.",
      },
      {
        id: "ro-3",
        question: "A Regulator role user can directly edit or delete borrower records from the Regulatory Dashboard.",
        correct: false,
        explanation: "Regulators have read-only access to borrower records. They can view data, run reports, and approve maker-checker submissions, but cannot directly create, edit, or delete records.",
      },
      {
        id: "ro-4",
        question: "The Compliance Queue shows records that have been flagged and are awaiting regulatory review or correction.",
        correct: true,
        explanation: "Correct. The Compliance Queue aggregates flagged records — including dispute escalations, SLA breaches, and data quality issues — in one place for efficient regulatory review.",
      },
      {
        id: "ro-5",
        question: "Cross-border credit searches can be performed by any user without any prior agreements.",
        correct: false,
        explanation: "Cross-border searches require a valid data-sharing agreement between the countries involved. The system enforces this — searches are blocked until an active agreement is on file.",
      },
      {
        id: "ro-6",
        question: "The BSL (Bank of Sierra Leone) export uses the same file format as the BoG (Bank of Ghana) export.",
        correct: false,
        explanation: "BSL and BoG exports use different formats that comply with each regulator's specific data standards. The system generates country-specific files automatically based on the target regulator.",
      },
      {
        id: "ro-7",
        question: "Regulators can approve or reject maker-checker submissions from institutions via the platform.",
        correct: true,
        explanation: "Correct. The Regulator role has approval rights in the maker-checker workflow. This ensures regulatory sign-off on significant data changes before they become permanent.",
      },
      {
        id: "ro-8",
        question: "The Regulatory Dashboard can be filtered by institution type, country, and date range.",
        correct: true,
        explanation: "Correct. All three filter dimensions are available, allowing regulators to drill into specific markets, institution categories, or time periods for targeted oversight.",
      },
    ],
  },
  {
    id: "loan-origination-collateral",
    title: "Loan Origination & Collateral Registry",
    description: "Full loan lifecycle management, 7 loan types, maker-checker approval, amortization schedules, collateral pledging, and asset tracking.",
    icon: "Banknote",
    color: "from-orange-500 to-orange-600",
    estimatedMinutes: 10,
    passPercent: 70,
    roles: ["super_admin", "admin", "lender"],
    questions: [
      {
        id: "lo-1",
        question: "A loan application submitted by a Lender must go through the maker-checker approval process before disbursement.",
        correct: true,
        explanation: "Correct. All loan origination submissions enter the maker-checker queue. An Admin or Super Admin must review and approve the application before funds can be disbursed.",
      },
      {
        id: "lo-2",
        question: "The Loan Origination module supports only one type of loan product.",
        correct: false,
        explanation: "The platform supports 7 loan types: Personal, Business, Mortgage, Auto, Education, Agriculture, and Microfinance — each with configurable terms, rates, and approval rules.",
      },
      {
        id: "lo-3",
        question: "An amortization schedule is automatically generated when a loan is approved and disbursed.",
        correct: true,
        explanation: "Correct. The system generates a full amortization schedule on disbursal, showing each repayment date, principal, interest, and outstanding balance for the full loan term.",
      },
      {
        id: "lo-4",
        question: "Collateral registered in the Collateral Registry can only be linked to one loan at a time.",
        correct: true,
        explanation: "Correct. Each collateral asset is linked to a single active loan. Attempting to pledge an already-encumbered asset against a second loan is blocked by the system.",
      },
      {
        id: "lo-5",
        question: "The Collateral Registry tracks asset type, value, location, document reference, and lien status.",
        correct: true,
        explanation: "Correct. Each collateral record stores asset type (land, vehicle, equipment, etc.), estimated value, geographic location, document reference number, and current lien status.",
      },
      {
        id: "lo-6",
        question: "Once a loan is disbursed, its terms (rate, tenure, amount) can be freely edited by any user.",
        correct: false,
        explanation: "Disbursed loan terms are locked. Modifications require a formal amendment process with maker-checker approval and are logged in the audit trail to preserve regulatory integrity.",
      },
      {
        id: "lo-7",
        question: "A Lender can approve their own loan application to speed up processing.",
        correct: false,
        explanation: "Maker-checker rules prohibit self-approval. The user who submits an application cannot be the same user who approves it — a separate authorized approver is always required.",
      },
      {
        id: "lo-8",
        question: "Releasing collateral from the Collateral Registry is only allowed after the linked loan is fully repaid.",
        correct: true,
        explanation: "Correct. The system enforces lien integrity — collateral can only be released (marked as unencumbered) once the linked loan reaches a Closed or Fully Repaid status.",
      },
    ],
  },
  {
    id: "billing-revenue",
    title: "Billing & Revenue Management",
    description: "Wallet and prepaid billing, transaction-based monetization, two-tier revenue split, institution fee management, and settlement & payout.",
    icon: "Wallet",
    color: "from-green-600 to-emerald-700",
    estimatedMinutes: 10,
    passPercent: 70,
    roles: ["super_admin"],
    questions: [
      {
        id: "br-1",
        question: "The platform uses a transaction-based billing model where institutions are charged per credit inquiry or report generated.",
        correct: true,
        explanation: "Correct. The monetization model is transaction-based. Each credit search, report generation, and API call is metered and billed against the institution's prepaid wallet balance.",
      },
      {
        id: "br-2",
        question: "The two-tier revenue split means 100% of transaction fees go directly to the platform operator.",
        correct: false,
        explanation: "The two-tier split divides revenue between the platform operator and the registered data provider. The split percentage is configurable per institution and per transaction type.",
      },
      {
        id: "br-3",
        question: "An institution's prepaid wallet balance can go negative without any restriction.",
        correct: false,
        explanation: "When a wallet balance reaches zero, API access and report generation are suspended for that institution until the wallet is topped up. Negative balances are not permitted.",
      },
      {
        id: "br-4",
        question: "Super Admins can view billing records, top-up history, and transaction logs from the Billing page.",
        correct: true,
        explanation: "Correct. The Billing page provides a full financial history per institution: wallet top-ups, transaction debits, revenue splits, payout records, and outstanding balances.",
      },
      {
        id: "br-5",
        question: "Settlement and payout to data providers is processed automatically based on a configurable schedule.",
        correct: true,
        explanation: "Correct. The settlement engine calculates each data provider's earned share and generates payout records on the configured cycle (daily, weekly, or monthly).",
      },
      {
        id: "br-6",
        question: "Institution Analytics shows usage metrics including the number of API calls, report generations, and search queries per day.",
        correct: true,
        explanation: "Correct. The Institution Analytics dashboard breaks down daily event counts by type — credit searches, report generations, batch uploads, and API calls — with billing impact shown alongside.",
      },
      {
        id: "br-7",
        question: "A Super Admin can set different fee rates for different transaction types within the same institution.",
        correct: true,
        explanation: "Correct. Fee structures are configurable per transaction type per institution. For example, credit report generation can carry a different fee than a basic credit search.",
      },
      {
        id: "br-8",
        question: "White-label branding for an institution (custom colors, logo, domain) is configured from the Billing page.",
        correct: false,
        explanation: "White-label branding is configured from the Institution Branding page, not the Billing page. Billing covers financial settings; branding covers visual identity and custom domain configuration.",
      },
    ],
  },
  {
    id: "data-management-export",
    title: "Data Management & Export",
    description: "Export Center with AES-256 encryption, retention policies, data subject erasure (GDPR), bulk upload (XBRL/IFF), and export history audit trail.",
    icon: "Database",
    color: "from-slate-600 to-slate-700",
    estimatedMinutes: 10,
    passPercent: 70,
    roles: ["super_admin", "admin"],
    questions: [
      {
        id: "dm-1",
        question: "The Export Center can produce a full data portability export of all borrowers, accounts, and audit logs.",
        correct: true,
        explanation: "Correct. The Export Center generates a comprehensive ZIP export covering borrowers, credit accounts, consent records, and audit logs — suitable for data portability or DR purposes.",
      },
      {
        id: "dm-2",
        question: "Exports from the Export Center can be optionally encrypted with AES-256 and verified with a SHA-256 integrity hash.",
        correct: true,
        explanation: "Correct. When encryption is enabled, the export is AES-256 encrypted with the passphrase you set. A SHA-256 hash is always generated so recipients can verify the file's integrity.",
      },
      {
        id: "dm-3",
        question: "Data retention policies can be configured to automatically archive or delete records older than a defined threshold.",
        correct: true,
        explanation: "Correct. Retention Policies define a country, data type, retention period, and enforcement action (flag, archive, or delete). The retention scanner enforces these on a scheduled basis.",
      },
      {
        id: "dm-4",
        question: "An Erasure Request permanently deletes all data linked to a borrower including credit accounts, consents, and audit logs.",
        correct: false,
        explanation: "Erasure Requests delete borrower PII and directly linked records, but audit logs are immutable and cannot be erased. This preserves the regulatory trail while honouring data subject rights.",
      },
      {
        id: "dm-5",
        question: "The IFF bulk upload format is used for importing structured credit data from international financial institutions.",
        correct: true,
        explanation: "Correct. The IFF (International Financial Format) upload accepts XML files from external institutions in a standardised format, enabling bulk import of structured credit portfolio data.",
      },
      {
        id: "dm-6",
        question: "Admins are rate-limited to 5 exports per hour to prevent system overload.",
        correct: true,
        explanation: "Correct. The export rate limiter allows a maximum of 5 exports per hour per Admin. Super Admins have the same limit in the standard configuration, and consumers are limited to 1 per day.",
      },
      {
        id: "dm-7",
        question: "The Retention Policy Scanner can be run globally across all countries by both Admin and Super Admin.",
        correct: false,
        explanation: "The Retention Policy Scanner is country-scoped for Admins (they only scan their own country's data). Super Admins can run a global scan across all countries simultaneously.",
      },
      {
        id: "dm-8",
        question: "The Export History tab provides an audit trail of all previous exports including who ran them and when.",
        correct: true,
        explanation: "Correct. Export History logs every export with timestamp, user, export type, record count, encryption status, and file size — providing a full chain of custody for all data exports.",
      },
    ],
  },
  {
    id: "consumer-onboarding",
    title: "Consumer Portal & Institution Onboarding",
    description: "Consumer self-service registration and credit checks, institution registration approval workflow, white-label branding, and fraud prevention.",
    icon: "UserCheck",
    color: "from-pink-500 to-rose-600",
    estimatedMinutes: 10,
    passPercent: 70,
    roles: ["super_admin", "admin"],
    questions: [
      {
        id: "co-1",
        question: "Consumers can register on the Consumer Portal without needing an admin to create their account first.",
        correct: true,
        explanation: "Correct. The Consumer Portal (/consumer/register) allows individuals to self-register using their national ID and personal details. Dual-channel verification (SMS + email) confirms identity.",
      },
      {
        id: "co-2",
        question: "Once registered on the Consumer Portal, individuals can view their credit score, accounts, and dispute history.",
        correct: true,
        explanation: "Correct. Authenticated consumers can view their bureau score, linked credit accounts, dispute history, consent records, and download their full credit report as a PDF.",
      },
      {
        id: "co-3",
        question: "A new institution can begin accessing borrower data immediately after completing the registration form.",
        correct: false,
        explanation: "Institution registration requires Super Admin approval before access is granted. The platform validates BRN (Business Registration Number), checks for duplicate entities, and flags fraud signals before approval.",
      },
      {
        id: "co-4",
        question: "The institution onboarding process includes Business Registration Number (BRN) validation to prevent fraudulent registrations.",
        correct: true,
        explanation: "Correct. BRN validation is part of the fraud prevention layer in institution onboarding. Duplicate BRNs, mismatched company details, and suspicious patterns trigger a hold for Super Admin review.",
      },
      {
        id: "co-5",
        question: "White-label branding allows each institution to set their own primary/secondary colors, logo, tagline, and custom domain.",
        correct: true,
        explanation: "Correct. The Institution Branding page allows full white-label customization: color palette, logo URL, tagline, support contact, footer text, and a custom domain — with a live portal preview.",
      },
      {
        id: "co-6",
        question: "Consumers can file disputes directly from the Consumer Portal without contacting the institution.",
        correct: true,
        explanation: "Correct. The Consumer Portal includes a dispute filing dialog where consumers select the dispute type, provide a description, and reference an account. The system creates a 5-business-day SLA case automatically.",
      },
      {
        id: "co-7",
        question: "Super Admins can approve, reject, or request more information from institutions awaiting onboarding approval.",
        correct: true,
        explanation: "Correct. The Institutions page shows all pending registrations with full details. Super Admins can approve, reject with a reason, or place on hold pending additional documentation.",
      },
      {
        id: "co-8",
        question: "Consumers are limited to one credit score lookup per day to prevent system abuse.",
        correct: true,
        explanation: "Correct. The Consumer Portal rate-limits credit score lookups to protect system resources and prevent misuse. The limit resets daily and is enforced per verified consumer account.",
      },
    ],
  },
  {
    id: "court-judgments-dishonoured-cheques",
    title: "Court Judgments & Dishonoured Cheques",
    description: "Court judgment record management (CCJs), dishonoured cheque registry, status lifecycles, credit impact, and adverse event reporting for regulators.",
    icon: "Gavel",
    color: "from-red-600 to-rose-700",
    estimatedMinutes: 10,
    passPercent: 70,
    roles: ["super_admin", "admin", "lender", "regulator"],
    questions: [
      {
        id: "cj-1",
        question: "Court judgment records in the platform are automatically sourced from judicial registries via the platform's court data integration.",
        correct: true,
        explanation: "Correct. The platform connects to court registries in supported jurisdictions to auto-import CCJ records. Manual entry is also available for jurisdictions without a direct integration.",
      },
      {
        id: "cj-2",
        question: "A satisfied court judgment (one where the debt has been paid) is removed immediately from the borrower's credit profile.",
        correct: false,
        explanation: "Satisfied judgments remain visible on the credit profile but are updated to 'Satisfied' status. They stay on record for a defined retention period — typically 6 years from the original judgment date, regardless of when they were settled.",
      },
      {
        id: "cj-3",
        question: "Dishonoured cheque records include the cheque number, amount, date, issuing bank, and reason for dishonour.",
        correct: true,
        explanation: "Correct. Each dishonoured cheque record captures full instrument details: cheque number, amount, presentation date, drawee bank, drawer account, and the specific dishonour reason (insufficient funds, account closed, signature mismatch, etc.).",
      },
      {
        id: "cj-4",
        question: "A lender can delete a dishonoured cheque record they submitted if they believe it was entered in error.",
        correct: false,
        explanation: "Submitted records cannot be self-deleted. To correct an erroneous entry the lender must raise a correction request, which enters the maker-checker workflow for admin approval. The original submission is preserved in the audit trail.",
      },
      {
        id: "cj-5",
        question: "The platform allows filtering court judgments by status — active, satisfied, vacated, and appealed.",
        correct: true,
        explanation: "Correct. The Court Judgments page offers status filtering so users can isolate active (enforceable) judgments from those that have been satisfied, vacated by the court, or are currently under appeal.",
      },
      {
        id: "cj-6",
        question: "Dishonoured cheques have no impact on a borrower's credit score calculation.",
        correct: false,
        explanation: "Dishonoured cheques are a negative signal factored directly into the credit score. Each recorded dishonour reduces the score and can trigger risk alerts, affecting the borrower's eligibility for future credit facilities.",
      },
      {
        id: "cj-7",
        question: "Regulators can view court judgment statistics aggregated across all institutions from the Regulatory Dashboard.",
        correct: true,
        explanation: "Correct. The Regulatory Dashboard includes an adverse event breakdown covering court judgments and dishonoured cheques by institution, giving regulators a system-wide view of adverse credit events.",
      },
      {
        id: "cj-8",
        question: "A court judgment record can be linked to a specific credit account or loan in the platform.",
        correct: true,
        explanation: "Correct. When entering or importing a court judgment it can be linked to the related credit account or loan. This linkage is displayed on the borrower's full credit report to give lenders complete context.",
      },
    ],
  },
  {
    id: "collections-debt-management",
    title: "Collections & Debt Management",
    description: "Full delinquency lifecycle from first missed payment through write-off or recovery, DPD buckets, Promise-to-Pay tracking, case assignment, and partial settlements.",
    icon: "DollarSign",
    color: "from-orange-600 to-red-600",
    estimatedMinutes: 10,
    passPercent: 70,
    roles: ["super_admin", "admin", "lender"],
    questions: [
      {
        id: "cd-1",
        question: "The Collections module tracks the full lifecycle of a delinquent account from first delinquency through to write-off or recovery.",
        correct: true,
        explanation: "Correct. The Collections module manages the end-to-end delinquency lifecycle: initial flagging, Promise-to-Pay tracking, escalation stages, legal referral, and final disposition — either recovery, negotiated settlement, or write-off.",
      },
      {
        id: "cd-2",
        question: "A Collection case is automatically created when a credit account misses its very first scheduled payment.",
        correct: false,
        explanation: "Collection cases are triggered based on configurable delinquency rules. The default is typically 30 days past due (DPD), not the first missed payment. Institutions can configure their own DPD threshold for case creation.",
      },
      {
        id: "cd-3",
        question: "The platform supports Promise-to-Pay (PTP) arrangements where a borrower commits to a future payment date.",
        correct: true,
        explanation: "Correct. Collection officers can log a Promise-to-Pay against a case, recording the agreed date and amount. The system tracks whether the promise is kept or broken, which influences escalation decisions automatically.",
      },
      {
        id: "cd-4",
        question: "Once a loan is written off, it is permanently removed from the platform's credit data.",
        correct: false,
        explanation: "Written-off accounts remain in the credit registry with a 'Written Off' status. They continue to appear on the borrower's credit report and affect the credit score — serving as a record of the default even after the creditor has absorbed the loss.",
      },
      {
        id: "cd-5",
        question: "The Collections dashboard provides a portfolio view of total outstanding delinquent amounts segmented by DPD bucket (30, 60, 90, 120+ days).",
        correct: true,
        explanation: "Correct. The dashboard segments the delinquent portfolio into standard DPD buckets — 1–30, 31–60, 61–90, and 91+ days past due — allowing managers to see concentration risk and prioritise recovery efforts effectively.",
      },
      {
        id: "cd-6",
        question: "Lenders can record partial payments and negotiated settlements against collection cases.",
        correct: true,
        explanation: "Correct. The system accepts partial payment records and negotiated settlement amounts against collection cases. Each payment reduces the outstanding balance and is logged in the case activity history for audit purposes.",
      },
      {
        id: "cd-7",
        question: "Collection cases can be assigned to specific collection agents or teams within the platform.",
        correct: true,
        explanation: "Correct. Cases can be assigned to named agents or agent pools. The system tracks case-level assignments, time-to-action, and resolution rates per agent — enabling performance management for collection teams.",
      },
      {
        id: "cd-8",
        question: "Closing a collection case automatically updates the linked credit account's status to 'Current'.",
        correct: false,
        explanation: "Closing a collection case (by marking it recovered, settled, or written off) updates the case status, but the linked credit account's payment status history remains unchanged. Credit account status is updated separately based on actual payment activity.",
      },
    ],
  },
  {
    id: "borrower-alerts-monitoring",
    title: "Borrower Alerts & Credit Monitoring",
    description: "Real-time credit event alerts, score threshold monitoring, multi-channel delivery, alert subscription rules, and the full alert history audit log.",
    icon: "Bell",
    color: "from-yellow-500 to-amber-600",
    estimatedMinutes: 8,
    passPercent: 70,
    roles: ["super_admin", "admin", "lender", "viewer"],
    questions: [
      {
        id: "ba-1",
        question: "Borrower Alerts notify subscribed users when a significant change occurs on a monitored borrower's credit profile.",
        correct: true,
        explanation: "Correct. The Borrower Alerts system sends real-time notifications when triggered events occur: a new credit inquiry, score change, new account opened, derogatory record added, or a dispute resolution — keeping lenders informed without manual checking.",
      },
      {
        id: "ba-2",
        question: "Any user role, including Viewer, can subscribe to alerts for any borrower in the system.",
        correct: false,
        explanation: "Alert subscriptions are restricted to borrowers the user's institution has a legitimate credit relationship with. Viewers can receive alerts on borrowers within their institution's portfolio but cannot subscribe to arbitrary borrowers outside their scope.",
      },
      {
        id: "ba-3",
        question: "Alert-triggering events include credit inquiries, score changes, new account openings, and dispute updates.",
        correct: true,
        explanation: "Correct. The alert engine covers a broad range of credit events: new credit inquiries, score threshold breaches, new accounts, payment status changes, new adverse records (court judgments, dishonoured cheques), and dispute status updates.",
      },
      {
        id: "ba-4",
        question: "Borrower Alerts are delivered via email only.",
        correct: false,
        explanation: "Alerts are delivered through multiple channels: in-platform notifications (the bell icon), email, and optionally via webhook to the institution's own systems. Users configure their preferred delivery channel in notification settings.",
      },
      {
        id: "ba-5",
        question: "A lender can set a score threshold alert so they are notified if a borrower's score drops below a defined level.",
        correct: true,
        explanation: "Correct. Score threshold alerts are configurable. A lender can specify 'notify me if this borrower's score drops below 550' — allowing proactive portfolio management before an account becomes delinquent.",
      },
      {
        id: "ba-6",
        question: "The Borrower Alerts page shows a full history of all alerts generated, including ones that have already been read.",
        correct: true,
        explanation: "Correct. The Alerts page maintains a complete history of all generated alerts — both unread and previously acknowledged. Each entry shows the event type, affected borrower, timestamp, and the specific data that changed.",
      },
      {
        id: "ba-7",
        question: "Super Admins can view alert activity across all institutions from the Borrower Alerts page.",
        correct: true,
        explanation: "Correct. Super Admins have a global view and can see alert activity across all institutions. This helps identify systemic credit events (e.g., widespread score drops in a sector) and monitor alert volume for capacity planning.",
      },
      {
        id: "ba-8",
        question: "Once a Borrower Alert is dismissed, it cannot be retrieved.",
        correct: false,
        explanation: "Dismissed alerts remain in the alert history with a 'Read' status. They are never permanently deleted — the full alert log is retained for audit and compliance purposes and can be scrolled through at any time.",
      },
    ],
  },
  {
    id: "consent-management",
    title: "Consent Management",
    description: "Consent-first data access model, consent channels (digital, SMS, paper), expiry and revocation rules, the consent audit trail, and Super Admin override authority.",
    icon: "ClipboardList",
    color: "from-teal-600 to-cyan-700",
    estimatedMinutes: 10,
    passPercent: 70,
    roles: ["super_admin", "admin", "lender"],
    questions: [
      {
        id: "cm-1",
        question: "Borrower consent must be obtained before a lender can access a borrower's credit report on the platform.",
        correct: true,
        explanation: "Correct. The platform enforces a consent-first model. Before generating a credit report or running a credit check on an individual borrower, the lender must have a recorded, active consent from that borrower — aligned with data protection regulations.",
      },
      {
        id: "cm-2",
        question: "A borrower can grant consent once and it remains permanently valid with no expiry.",
        correct: false,
        explanation: "Consent records have a configurable expiry period (typically 12–24 months). Once expired, lenders must obtain fresh consent before accessing the borrower's data again. The platform tracks expiry dates and warns users before a consent lapses.",
      },
      {
        id: "cm-3",
        question: "The Consent Management page allows admins to view all active, expired, and revoked consents for their institution.",
        correct: true,
        explanation: "Correct. The Consent Management page presents a filterable list of all consent records — active, expired, pending, and revoked — with borrower ID, consent channel, grant date, expiry date, and the purpose stated at the time of consent.",
      },
      {
        id: "cm-4",
        question: "A borrower who revokes their consent loses all existing credit data from the registry immediately.",
        correct: false,
        explanation: "Revoking consent stops future data access by the lender who held that consent. Historical credit data already in the registry is not deleted by a revocation — it remains available to other lenders who hold separate valid consents or to regulators.",
      },
      {
        id: "cm-5",
        question: "The platform supports digital e-consent, SMS OTP consent, and paper consent upload as valid consent channels.",
        correct: true,
        explanation: "Correct. Consent can be recorded from any of three channels: digital (borrower signs online), SMS (confirmed via OTP), or paper (physical form scanned and uploaded with a document reference). All channels produce a verifiable consent record.",
      },
      {
        id: "cm-6",
        question: "A lender must obtain a separate consent for each type of data access (credit report, credit score, inquiry).",
        correct: false,
        explanation: "A single consent record can cover multiple access types as specified in the consent purpose declaration. However, the declared purposes must be explicit — a consent granted for 'credit scoring' cannot also be used for full report generation without that purpose being listed.",
      },
      {
        id: "cm-7",
        question: "The Consent Audit Trail shows every access event linked to each consent record, creating a complete chain of custody.",
        correct: true,
        explanation: "Correct. Each consent record carries a linked access log showing every credit check, report generation, or data access made under that consent. This chain of custody is available to regulators and, in some cases, to the borrower on request.",
      },
      {
        id: "cm-8",
        question: "Super Admins can revoke an institution's consent grants on behalf of a borrower who has made a formal complaint.",
        correct: true,
        explanation: "Correct. In cases of formal complaints or regulatory directives, Super Admins have the authority to revoke specific consent grants. The revocation is logged with reason and reflected immediately — the institution loses access to the affected borrower's data.",
      },
    ],
  },
  {
    id: "decision-engine",
    title: "Decision Engine & Credit Rules",
    description: "Rules-based automated credit decisioning, multi-factor rule sets, product-specific configurations, Approve/Decline/Refer outcomes, explainability logs, and override governance.",
    icon: "Cpu",
    color: "from-indigo-600 to-violet-700",
    estimatedMinutes: 10,
    passPercent: 70,
    roles: ["super_admin", "admin"],
    questions: [
      {
        id: "de-1",
        question: "The Decision Engine allows institutions to define automated credit decision rules that run against a borrower's credit profile.",
        correct: true,
        explanation: "Correct. The Decision Engine is a rules-based automation layer. Institutions configure rule sets (score thresholds, DPD limits, balance caps, etc.) that trigger automated Approve, Decline, or Refer decisions without manual intervention.",
      },
      {
        id: "de-2",
        question: "Decision rules can only be based on the bureau credit score.",
        correct: false,
        explanation: "Rules can combine multiple data points: bureau score, number of open accounts, highest DPD in the last 12 months, total outstanding balance, presence of court judgments, dishonoured cheques, and custom calculated fields — enabling nuanced multi-factor decisioning.",
      },
      {
        id: "de-3",
        question: "A Rule Set can be activated and deactivated without deleting it, allowing institutions to test rules before going live.",
        correct: true,
        explanation: "Correct. Rule sets have a status toggle (Active/Inactive). Institutions typically build and test a new rule set in inactive mode — running it in simulation against historical data — before switching it to active for live decisioning.",
      },
      {
        id: "de-4",
        question: "Once a Decision Engine rule rejects a loan application, the decision cannot be overridden by a human reviewer.",
        correct: false,
        explanation: "Automated decisions can always be reviewed and overridden by an authorised user (Admin or above). All overrides are logged with the reviewer's identity and override reason, creating a full audit trail that satisfies regulatory fair-lending requirements.",
      },
      {
        id: "de-5",
        question: "The Decision Engine logs every automated decision with the specific rules triggered, data values evaluated, and final outcome.",
        correct: true,
        explanation: "Correct. Every decision generates a detailed log entry: the rule set version used, each rule evaluated (pass/fail), the data values at the time of evaluation, and the final decision. This explainability log supports regulatory compliance and borrower appeals.",
      },
      {
        id: "de-6",
        question: "Institutions can create multiple rule sets for different loan products — for example, separate rules for mortgages and micro-loans.",
        correct: true,
        explanation: "Correct. Rule sets are product-scoped. An institution can maintain distinct rule sets for Personal Loans, Micro-loans, Mortgages, and Business Loans — each with thresholds that reflect the risk profile of that product type.",
      },
      {
        id: "de-7",
        question: "A Decision Engine 'Refer' outcome means the application is automatically declined after a set waiting period.",
        correct: false,
        explanation: "A Refer outcome escalates the application to a human credit analyst for manual review — it does not auto-decline. The analyst can approve, decline, or request additional information after reviewing the full application file.",
      },
      {
        id: "de-8",
        question: "Super Admins can view Decision Engine usage statistics across all institutions, including approval rates and override frequencies.",
        correct: true,
        explanation: "Correct. Super Admins have a platform-wide view of Decision Engine metrics: approval/decline/refer ratios, override rates, rule-set utilisation, and decision volume by institution — enabling monitoring for bias, consistency, and system health.",
      },
    ],
  },
  {
    id: "portfolio-intelligence",
    title: "Portfolio Intelligence & Analytics",
    description: "Aggregated portfolio analytics, NPL ratios, vintage analysis, concentration risk, score distribution, sector and geographic breakdowns, and exportable board reports.",
    icon: "BarChart",
    color: "from-emerald-500 to-teal-600",
    estimatedMinutes: 10,
    passPercent: 70,
    roles: ["super_admin", "admin", "regulator"],
    questions: [
      {
        id: "pi-1",
        question: "Portfolio Intelligence provides aggregated analytics on the credit portfolio across dimensions including sector, geography, and loan type.",
        correct: true,
        explanation: "Correct. Portfolio Intelligence aggregates credit data across borrower segments, industry sectors, geographies, and loan product types — turning raw portfolio data into actionable intelligence for risk managers and regulators.",
      },
      {
        id: "pi-2",
        question: "The Non-Performing Loan (NPL) ratio shown in Portfolio Intelligence is calculated in real time based on current account statuses.",
        correct: true,
        explanation: "Correct. NPL ratios are computed dynamically from live account status data using the standard definition (90+ DPD or subjective assessment). They can be filtered by institution, sector, or country for granular analysis.",
      },
      {
        id: "pi-3",
        question: "Portfolio Intelligence can only display data for the current calendar month.",
        correct: false,
        explanation: "Portfolio Intelligence supports configurable time ranges — last 30 days, 90 days, 6 months, 12 months, or a custom date range. Historical trending charts show how portfolio metrics have evolved over time, enabling period-over-period comparisons.",
      },
      {
        id: "pi-4",
        question: "Concentration risk analysis shows whether a portfolio is over-exposed to a single sector, borrower type, or geography.",
        correct: true,
        explanation: "Correct. Concentration risk analysis highlights segments where exposure exceeds safe thresholds. Alerts can be configured to flag when concentration limits are breached — for example, if more than 40% of outstanding balances are in one sector.",
      },
      {
        id: "pi-5",
        question: "Regulators can access Portfolio Intelligence analytics only for institutions they are directly assigned to oversee.",
        correct: false,
        explanation: "Regulators have a cross-institution view within their jurisdiction. They can analyse the aggregate portfolio across all regulated institutions in their country — sector concentration, NPL trends, vintage analysis — without being locked to a single institution.",
      },
      {
        id: "pi-6",
        question: "Vintage analysis tracks the performance of loans by the period they were originated, enabling assessment of underwriting quality over time.",
        correct: true,
        explanation: "Correct. Vintage analysis groups loans by origination cohort and tracks their cumulative default rates as they age. It is one of the most powerful tools for identifying deteriorating underwriting standards before they become systemic.",
      },
      {
        id: "pi-7",
        question: "Portfolio Intelligence includes a scorecard breakdown showing the distribution of borrowers across credit score bands.",
        correct: true,
        explanation: "Correct. The Score Distribution view shows how the borrower population is spread across score bands (Poor, Fair, Good, Very Good, Excellent). This helps identify portfolio risk concentration in lower score bands.",
      },
      {
        id: "pi-8",
        question: "Data in Portfolio Intelligence can be exported as CSV or PDF for use in board reporting.",
        correct: true,
        explanation: "Correct. All Portfolio Intelligence dashboards and tables support CSV export (for further analysis in Excel or BI tools) and PDF export (for board packs and regulatory submissions). All exports are logged in the audit trail.",
      },
    ],
  },
  {
    id: "telco-lending-scoring",
    title: "Telco Lending & Scoring",
    description: "Alternative credit scoring from mobile network data, telco micro-loan origination and disbursement via mobile money, per-country model calibration, and bureau integration.",
    icon: "Smartphone",
    color: "from-sky-500 to-blue-600",
    estimatedMinutes: 10,
    passPercent: 70,
    roles: ["super_admin", "admin", "lender"],
    questions: [
      {
        id: "ts-1",
        question: "Telco Scoring uses mobile usage data — such as top-up frequency, data consumption, and call patterns — to generate a credit score for borrowers with limited formal credit history.",
        correct: true,
        explanation: "Correct. The Telco Scoring model uses anonymised mobile network behaviour as alternative credit data. Regular airtime top-ups, consistent data usage, and stable network activity are positive signals for thin-file borrowers who lack a formal credit trail.",
      },
      {
        id: "ts-2",
        question: "A Telco Score replaces the bureau credit score on the credit report.",
        correct: false,
        explanation: "The Telco Score is a supplementary signal — it adds to, but does not replace, the bureau score. On the credit report both scores are presented separately. The Telco Score is especially valuable for thin-file borrowers where the bureau score has low confidence.",
      },
      {
        id: "ts-3",
        question: "Telco Lending products are short-term micro-loans disbursed directly to a borrower's mobile money wallet based on their Telco Score.",
        correct: true,
        explanation: "Correct. Telco Lending enables mobile-network-based micro-loan origination. Loans are typically small, short-term, and disbursed to the borrower's mobile money wallet — making credit accessible to unbanked and underbanked populations.",
      },
      {
        id: "ts-4",
        question: "Telco usage data is stored permanently on the credit registry for use in all future credit decisions.",
        correct: false,
        explanation: "Telco data access is governed by time-limited consent. Usage data is processed at the point of scoring and is not stored permanently in the registry. Each telco query requires a fresh data pull within the consent window, and retention follows the configured policy.",
      },
      {
        id: "ts-5",
        question: "The Telco Scoring model can be calibrated differently per country to reflect local network usage patterns.",
        correct: true,
        explanation: "Correct. Network behaviour patterns vary significantly across markets. The Telco Scoring model supports per-country calibration, adjusting feature weightings to reflect local patterns for better predictive accuracy in each market.",
      },
      {
        id: "ts-6",
        question: "Borrowers must explicitly consent to their telco data being used for credit scoring before a Telco Score can be generated.",
        correct: true,
        explanation: "Correct. Telco data consent is captured separately from general credit consent. The borrower must agree specifically to the use of their mobile network data for credit assessment — this consent is recorded and linked to the telco scoring event.",
      },
      {
        id: "ts-7",
        question: "Telco loans disbursed through the platform are automatically reported to the credit registry and appear on the borrower's credit profile.",
        correct: true,
        explanation: "Correct. Loan events (disbursement, repayment, missed payment, closure) generated through the Telco Lending module are automatically submitted to the credit registry — meaning telco loans build or damage the borrower's credit profile just like any other facility.",
      },
      {
        id: "ts-8",
        question: "Super Admins can monitor Telco Scoring volumes, average scores, and model drift indicators from the Telco Scoring administration page.",
        correct: true,
        explanation: "Correct. The Telco Scoring admin page provides operational metrics: daily scoring volumes, average score by cohort, feature importance stability to detect model drift, and error/timeout rates for telco data connections.",
      },
    ],
  },
  {
    id: "papss-settlements",
    title: "PAPSS Settlements & International Payments",
    description: "Pan-African Payment and Settlement System integration, cross-border revenue remittances in local African currencies, settlement batch management, and status reconciliation.",
    icon: "Globe",
    color: "from-green-500 to-emerald-600",
    estimatedMinutes: 10,
    passPercent: 70,
    roles: ["super_admin", "admin"],
    questions: [
      {
        id: "ps-1",
        question: "PAPSS stands for the Pan-African Payment and Settlement System — the continent's cross-border instant payment infrastructure.",
        correct: true,
        explanation: "Correct. PAPSS is the African Union-backed payment infrastructure that enables instant, low-cost cross-border payments in local African currencies — reducing reliance on correspondent banking and dollar-denominated settlement.",
      },
      {
        id: "ps-2",
        question: "PAPSS Settlements in the platform are used to process cross-border revenue remittances between institutions in different African countries.",
        correct: true,
        explanation: "Correct. The PAPSS Settlements module handles inter-country financial flows between participating registry members — including data provider revenue payouts, licence fee remittances, and other cross-border institutional payments settled through PAPSS infrastructure.",
      },
      {
        id: "ps-3",
        question: "All African countries are currently connected to PAPSS, so cross-border settlements can be made to any African nation.",
        correct: false,
        explanation: "PAPSS onboarding is ongoing — not all African nations are connected yet. The platform shows which countries are live on PAPSS and routes settlements accordingly. Payments to non-PAPSS countries may require alternative routing through SWIFT or correspondent banking.",
      },
      {
        id: "ps-4",
        question: "PAPSS settlements are always processed in US dollars to ensure cross-border stability.",
        correct: false,
        explanation: "PAPSS is specifically designed to settle in local African currencies — Ghanaian Cedi, Nigerian Naira, Sierra Leonean Leone, etc. — without converting through USD. This is one of PAPSS's core design goals and a key benefit over traditional correspondent banking.",
      },
      {
        id: "ps-5",
        question: "A Super Admin can initiate, review, and confirm PAPSS settlement batches from the PAPSS Settlements page.",
        correct: true,
        explanation: "Correct. The PAPSS Settlements page gives Super Admins a full workflow: build a settlement batch, review beneficiary details and amounts, confirm the batch for submission to the PAPSS gateway, and monitor settlement status in real time.",
      },
      {
        id: "ps-6",
        question: "Settlement status updates from PAPSS — such as Pending, Cleared, and Rejected — are reflected automatically in the platform.",
        correct: true,
        explanation: "Correct. The platform maintains a live status sync with the PAPSS gateway. Settlement statuses update automatically as PAPSS processes each item — Pending → In Transit → Cleared, or Pending → Rejected with a rejection reason code.",
      },
      {
        id: "ps-7",
        question: "Failed PAPSS settlements are automatically retried without any notification to the Super Admin.",
        correct: false,
        explanation: "Failed settlements are NOT automatically retried — they are flagged for manual review. The Super Admin receives an in-platform notification and email alert and must investigate the rejection reason before re-submitting or routing the payment via an alternative method.",
      },
      {
        id: "ps-8",
        question: "PAPSS settlement records are included in the platform's Export Centre and audit trail for regulatory reporting.",
        correct: true,
        explanation: "Correct. All PAPSS settlement transactions are captured in the audit trail and are exportable from the Export Centre — creating a full, traceable financial record for regulatory reporting, FX reconciliation, and external audits.",
      },
    ],
  },
  {
    id: "predictive-default-risk",
    title: "Predictive Default Risk & ML Scoring",
    description: "African-market ML credit scoring model, predictive default risk API, cross-lender risk alerts, open banking data integration, and risk card interpretation.",
    icon: "TrendingDown",
    color: "from-red-500 to-rose-600",
    estimatedMinutes: 10,
    passPercent: 70,
    roles: ["super_admin", "admin", "lender", "regulator"],
    questions: [
      {
        id: "pdr-1",
        question: "The Predictive Default Risk score is generated by a machine learning model trained specifically on African credit market data.",
        correct: true,
        explanation: "Correct. The ML scoring model incorporates African-specific risk factors including mobile money repayment history, agricultural income seasonality, informal economy indicators, and local macroeconomic variables — signals absent from models built on Western credit datasets.",
      },
      {
        id: "pdr-2",
        question: "The Predictive Default Risk API always returns a risk score regardless of how much data is available for a borrower.",
        correct: false,
        explanation: "The API requires a minimum data threshold to return a reliable prediction. For thin-file borrowers with insufficient history, the endpoint returns a low-confidence flag rather than a potentially misleading score.",
      },
      {
        id: "pdr-3",
        question: "The Default Risk Card on the borrower detail page is hidden when a borrower's risk level is assessed as Low.",
        correct: true,
        explanation: "Correct. The Default Risk Card only surfaces when the ML model detects an elevated or high risk level. For low-risk borrowers the card is intentionally hidden to keep the UI clean and draw attention only where action may be needed.",
      },
      {
        id: "pdr-4",
        question: "Cross-lender risk alerts notify a lender when a borrower they hold has taken on new credit obligations at another institution.",
        correct: true,
        explanation: "Correct. Cross-lender alerts fire when the platform detects a borrower's aggregate credit exposure has changed due to activity at another lender. This allows proactive portfolio management — catching over-indebtedness before it becomes default.",
      },
      {
        id: "pdr-5",
        question: "Open banking data from MTN MoMo, GCB Bank, Flutterwave, and Orange Money can be linked to a borrower profile to enhance credit assessment.",
        correct: true,
        explanation: "Correct. The Open Banking card on the borrower detail page supports linking to multiple African open banking providers — including MTN MoMo, GCB Bank, Flutterwave, and Orange Money — enriching the credit file with real transaction-level cashflow data.",
      },
      {
        id: "pdr-6",
        question: "Agricultural income seasonality is a risk factor unique to the Africa Credit Hub ML model and not used by any global bureau.",
        correct: true,
        explanation: "Correct. African economies have a significantly higher proportion of agricultural borrowers with seasonal income patterns. The ACH ML model explicitly weights seasonal income volatility as a risk factor — a factor global bureaus do not model for African markets.",
      },
      {
        id: "pdr-7",
        question: "The Default Risk endpoint's 'warnings' field lists specific risk factors that drove the elevated score, enabling explainability.",
        correct: true,
        explanation: "Correct. The API response includes a warnings array of human-readable risk signals (e.g. 'Multiple new inquiries in 30 days', 'DPD spike in last quarter') providing lenders with explainable AI outputs that satisfy regulatory requirements for credit decision transparency.",
      },
      {
        id: "pdr-8",
        question: "The predictive default risk score replaces the traditional bureau credit score for all credit decisions.",
        correct: false,
        explanation: "The predictive default risk score is a supplementary signal used alongside the bureau score — it does not replace it. Lenders use both: the bureau score for point-in-time creditworthiness and the default risk score for forward-looking default probability, especially for portfolio monitoring.",
      },
    ],
  },
  {
    id: "regulatory-exports-cbk-cbn",
    title: "Regulatory Exports: CBK, CBN & DVLA/Lands Collateral",
    description: "CBK (Central Bank of Kenya) and CBN (Central Bank of Nigeria) export formats, collateral verification via DVLA and Ghana Lands Commission, multi-jurisdiction filing workflow.",
    icon: "FileDown",
    color: "from-indigo-500 to-blue-600",
    estimatedMinutes: 10,
    passPercent: 70,
    roles: ["super_admin", "admin", "regulator"],
    questions: [
      {
        id: "rec-1",
        question: "The CBK (Central Bank of Kenya) export generates a compliance file in the exact format required by Kenya's credit reporting regulations.",
        correct: true,
        explanation: "Correct. The CBK export is pre-built to the Central Bank of Kenya's credit registry submission specification. Admins can generate and download the file directly from the Regulatory Exports page — no custom development or manual formatting required.",
      },
      {
        id: "rec-2",
        question: "The CBN (Central Bank of Nigeria) export follows the same file format as the CBK export since both are central bank formats.",
        correct: false,
        explanation: "CBK and CBN exports use different formats, each aligned to their respective regulator's specification. The platform generates country-specific files automatically. Using the wrong format would cause a submission rejection by the receiving central bank.",
      },
      {
        id: "rec-3",
        question: "The sidebar shows CBK and CBN export links simultaneously regardless of the active country mode.",
        correct: false,
        explanation: "Export links are context-sensitive: the CBK export appears in Kenya mode, CBN in Nigeria mode, and BoG in Ghana mode. In the default mode (Ghana), BoG and CBN links are both visible. Switching country modes updates the sidebar to show the relevant regulator links.",
      },
      {
        id: "rec-4",
        question: "The DVLA verification panel appears in the collateral registration form when the collateral type is a vehicle or motor vehicle.",
        correct: true,
        explanation: "Correct. When registering collateral of type 'vehicle' or class 'motor vehicle', the DVLA (Driver and Vehicle Licensing Authority) panel automatically appears in Step 2 of the form. It captures the DVLA reference number, registration plate, chassis number, make, model, colour, and year.",
      },
      {
        id: "rec-5",
        question: "The Ghana Lands Commission verification panel is used to validate land and real estate collateral.",
        correct: true,
        explanation: "Correct. For collateral types of 'land' or 'real estate', the Lands Commission panel appears in the collateral registration form. It captures the Lands Commission reference, title deed number, land size, location district, and deed registration date — enabling formal verification of land title.",
      },
      {
        id: "rec-6",
        question: "DVLA and Lands Commission verification panels are visible for all collateral types, not just vehicles and land.",
        correct: false,
        explanation: "Both panels are conditional and context-sensitive. The DVLA panel only appears for vehicle/motor vehicle collateral; the Lands Commission panel only for land/real estate. Other collateral types (equipment, financial instruments) show neither panel.",
      },
      {
        id: "rec-7",
        question: "A regulator with read-only access can generate and download CBK or CBN export files from the Regulatory Exports page.",
        correct: true,
        explanation: "Correct. Export generation is a read-only operation — it compiles existing registry data into a formatted file. Regulators can generate and download these files as part of their oversight function without needing write access to borrower records.",
      },
      {
        id: "rec-8",
        question: "Regulatory export files are included in the platform's audit trail showing who generated the export and when.",
        correct: true,
        explanation: "Correct. Every regulatory export — BoG, BSL, CBK, CBN — is logged in the audit trail with the generating user's identity, timestamp, record count, and export type. This creates a complete chain of custody for all regulatory submissions.",
      },
    ],
  },
  {
    id: "backup-system-status",
    title: "Backup & System Status",
    description: "Automated and on-demand database backups, AES-256 encrypted snapshots, GFS retention rotation, restoration governance, and real-time component health monitoring.",
    icon: "Server",
    color: "from-gray-600 to-slate-700",
    estimatedMinutes: 8,
    passPercent: 70,
    roles: ["super_admin"],
    questions: [
      {
        id: "bss-1",
        question: "The Backup page allows Super Admins to manually trigger a full database backup in addition to the automated daily backup schedule.",
        correct: true,
        explanation: "Correct. Automated backups run daily at 00:00 UTC. Super Admins can also trigger an on-demand backup at any time — for example, before a major migration or configuration change — with a custom label for easy identification.",
      },
      {
        id: "bss-2",
        question: "Backup files are stored unencrypted so they can be quickly restored in an emergency.",
        correct: false,
        explanation: "All backup files are encrypted at rest using AES-256 before storage. Decryption requires the platform's backup key. This ensures backup files cannot be read even if the storage medium is physically compromised.",
      },
      {
        id: "bss-3",
        question: "The platform retains the last 30 daily backup snapshots before older ones are automatically purged.",
        correct: true,
        explanation: "Correct. The default retention policy keeps 30 daily snapshots, 4 weekly snapshots, and 3 monthly snapshots — a standard grandfather-father-son (GFS) backup rotation. Super Admins can view all available restore points from the Backup page.",
      },
      {
        id: "bss-4",
        question: "Restoring from a backup can be triggered directly from the Backup page without any additional confirmation step.",
        correct: false,
        explanation: "Restoration is a destructive, irreversible operation that overwrites the live database. The platform requires an explicit multi-step confirmation: the Super Admin must type a confirmation phrase and approve a secondary prompt before restoration begins.",
      },
      {
        id: "bss-5",
        question: "The System Status page shows real-time health indicators for all platform components including the database, email service, SMS gateway, and exchange rate feeds.",
        correct: true,
        explanation: "Correct. System Status provides a live health dashboard for every platform dependency: PostgreSQL database, SMTP email, SMS/Twilio gateway, exchange rate scheduler, WebSocket server, PAPSS gateway, and backup service — with uptime percentages and last-checked timestamps.",
      },
      {
        id: "bss-6",
        question: "If the exchange rate sync service is failing, it appears as 'Degraded' on the System Status page and a Super Admin alert is triggered.",
        correct: true,
        explanation: "Correct. Service health states are Healthy (green), Degraded (yellow — partial failure), and Down (red — complete failure). Each state change triggers an in-platform notification and email to all Super Admins so the team is immediately aware.",
      },
      {
        id: "bss-7",
        question: "The detailed System Status page with component-level health metrics is accessible to all user roles.",
        correct: false,
        explanation: "The detailed System Status page — with component-level health, internal metrics, and dependency graphs — is restricted to Super Admins. A simplified public status indicator may be visible to other users showing only whether the system is operational or degraded.",
      },
      {
        id: "bss-8",
        question: "The Backup page includes a download option so Super Admins can retrieve an encrypted backup file for off-site archiving.",
        correct: true,
        explanation: "Correct. Super Admins can download any available backup snapshot as an encrypted archive for off-site storage or DR (Disaster Recovery) testing. The download is logged in the audit trail with the user's identity and timestamp.",
      },
    ],
  },
];

export function getModules(lang: string): TrainingModule[] {
  const t = TRAINING_TRANSLATIONS[lang] ?? TRAINING_TRANSLATIONS["en"];
  const translated = MODULE_META.map((meta) => {
    const tx = t[meta.tKey];
    return {
      id: meta.id,
      title: tx.title,
      description: tx.description,
      icon: meta.icon,
      color: meta.color,
      estimatedMinutes: meta.estimatedMinutes,
      passPercent: meta.passPercent,
      roles: meta.roles,
      questions: meta.questions.map((q) => ({
        id: q.id,
        question: tx[q.qk],
        correct: q.correct,
        explanation: tx[q.ek],
      })),
    };
  });
  return [...translated, ...HARDCODED_MODULES];
}

export function getModulesForRole(lang: string, role: UserRole): TrainingModule[] {
  return getModules(lang).filter((m) => m.roles.includes(role));
}

export const ROLE_LABELS: Record<UserRole, string> = {
  super_admin: "Super Admin",
  admin: "Administrator",
  lender: "Lender",
  regulator: "Regulator",
  viewer: "Viewer",
};

export const ROLE_DESCRIPTIONS: Record<UserRole, string> = {
  super_admin: "Your training covers all 23 modules — full platform coverage including predictive default risk & ML scoring, regulatory exports (CBK/CBN/DVLA/Lands Commission), court judgments, dishonoured cheques, collections, borrower alerts, consent management, decision engine, portfolio intelligence, telco lending & scoring, PAPSS settlements, backup & system status, plus platform navigation, credit operations, AI tools, loan origination & collateral, billing & revenue, data management & export, consumer portal, administration, system configuration, and regulatory reporting.",
  admin: "Your training covers 21 modules — platform navigation, borrower management, credit operations, disputes, AI tools, loan origination & collateral, data management & export, consumer portal, regulatory reporting, court judgments & dishonoured cheques, collections, borrower alerts, consent management, decision engine, portfolio intelligence, telco lending & scoring, PAPSS settlements, predictive default risk & ML scoring, regulatory exports (CBK/CBN/DVLA/Lands Commission), and administration & roles.",
  lender: "Your training covers 12 modules — platform navigation, borrower management, credit accounts & scoring, disputes & compliance, AI & cross-border tools, loan origination & collateral, court judgments & dishonoured cheques, collections & debt management, borrower alerts & monitoring, consent management, telco lending & scoring, and predictive default risk & ML scoring.",
  regulator: "Your training covers 8 modules — platform navigation, disputes & compliance, AI & cross-border analytics, regulatory oversight & reporting, court judgments & dishonoured cheques, portfolio intelligence & analytics, predictive default risk & ML scoring, and regulatory exports (CBK/CBN/DVLA/Lands Commission).",
  viewer: "Your training covers 3 modules — platform navigation, borrower management, and borrower alerts & credit monitoring so you can confidently find, read, and stay informed on credit records.",
};

export const OVERALL_PASS_PERCENT = 70;
