import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: './e2e',
  testMatch: '**/*.spec.ts',
  fullyParallel: false,
  retries: 0,
  timeout: 60000,
  workers: 1,
  globalSetup: './e2e/global-setup.ts',
  projects: [
    {
      name: 'unauthenticated',
      testMatch: ['auth.spec.ts', 'error-handling.spec.ts', 'security-auth-extended.spec.ts', 'external-api.spec.ts'],
      use: {
        baseURL: 'http://localhost:5000',
        headless: true,
        screenshot: 'only-on-failure',
        trace: 'retain-on-failure',
      },
    },
    {
      name: 'authenticated',
      testMatch: [
        'dashboard-navigation.spec.ts',
        'borrowers.spec.ts',
        'borrower-data-extended.spec.ts',
        'credit-accounts.spec.ts',
        'credit-reports-extended.spec.ts',
        'search.spec.ts',
        'super-admin.spec.ts',
        'compliance.spec.ts',
        'operations-disputes-consent.spec.ts',
        'reports-regulatory.spec.ts',
        'regulatory-compliance-extended.spec.ts',
        'supporting-pages.spec.ts',
        'admin-configuration.spec.ts',
        'telco-scoring-lending.spec.ts',
        'cross-border-papss.spec.ts',
        'ai-command-center.spec.ts',
        'platform-command-center.spec.ts',
        'sla-performance.spec.ts',
        'consumer-portal-docs.spec.ts',
        'mfa-session-security.spec.ts',
      ],
      use: {
        baseURL: 'http://localhost:5000',
        headless: true,
        screenshot: 'only-on-failure',
        trace: 'retain-on-failure',
        storageState: 'e2e/.auth/storage-state.json',
      },
    },
  ],
  reporter: [['list'], ['html', { open: 'never', outputFolder: 'e2e/report' }]],
  outputDir: 'e2e/test-results-artifacts',
});
