import { useQuery } from "@tanstack/react-query";
import type { ReactNode } from "react";
import { Activity, ShieldAlert, UserCheck } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

type Reviewer = { user_id:string|null; full_name:string; email?:string; role?:string; activity_count:number; ip_count:number; sensitive_count:number; actions:string[]; last_activity:string; score:number; severity:"high"|"elevated"|"review"; signals:string[] };
export default function InsiderRiskReviewPage() {
  const { data, isLoading } = useQuery<{generatedAt:string;reviewers:Reviewer[]}>({ queryKey:["/api/insider-risk-review"] });
  const reviewers=data?.reviewers||[];
  return <main className="mx-auto max-w-6xl space-y-6 p-4 md:p-8" data-testid="insider-risk-review"><header><p className="text-xs font-semibold uppercase tracking-widest text-primary">Privileged-access control</p><h1 className="mt-2 text-3xl font-bold">Insider Risk Review</h1><p className="mt-2 max-w-3xl text-muted-foreground">Explainable activity signals from the tamper-evident audit trail. These are review priorities—not findings of misconduct—and no staff action is automated.</p></header><section className="grid gap-4 md:grid-cols-3"><Metric icon={<ShieldAlert className="text-red-600"/>} value={reviewers.filter(item=>item.severity === "high").length} label="High-priority reviews"/><Metric icon={<UserCheck className="text-amber-600"/>} value={reviewers.length} label="Staff/system reviews"/><Metric icon={<Activity className="text-primary"/>} value={reviewers.reduce((sum,item)=>sum+Number(item.activity_count),0)} label="Flagged actions (24h)"/></section><Card><CardHeader><CardTitle>Review priorities</CardTitle><CardDescription>Signals include sensitive actions, unusually high activity, and multiple source IPs. Use the Audit Trail for the underlying, hash-verified evidence.</CardDescription></CardHeader><CardContent>{isLoading?<p>Loading…</p>:reviewers.length?<div className="space-y-3">{reviewers.map((item,index)=><article key={`${item.user_id||"system"}-${index}`} className="rounded-lg border p-4"><div className="flex flex-col justify-between gap-2 sm:flex-row"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{item.full_name}</p><Badge variant={item.severity === "high" ? "destructive" : "secondary"}>{item.severity} · {item.score}/100</Badge></div><p className="mt-1 text-sm text-muted-foreground">{item.email||"No current account record"} · {item.role||"system"}</p></div><p className="text-sm text-muted-foreground">Last activity {new Date(item.last_activity).toLocaleString()}</p></div><p className="mt-3 text-sm">{item.signals.join(" · ")}</p><p className="mt-2 text-xs text-muted-foreground">Observed actions: {(item.actions||[]).join(", ")}</p></article>)}</div>:<p className="py-8 text-center text-muted-foreground">No staff activity currently meets the review threshold.</p>}</CardContent></Card></main>;
}
function Metric({icon,value,label}:{icon:ReactNode;value:number;label:string}) { return <Card><CardContent className="flex items-center gap-3 p-5"><div>{icon}</div><div><p className="text-2xl font-bold">{value}</p><p className="text-sm text-muted-foreground">{label}</p></div></CardContent></Card>; }
