import { useState } from "react";
import { useTranslation } from "react-i18next";
import { useQuery, useMutation } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { useToast } from "@/hooks/use-toast";
import { queryClient, apiRequest } from "@/lib/queryClient";
import { MessageCircle, RefreshCw, AlertTriangle, CheckCircle2, Clock, XCircle } from "lucide-react";

interface MessagingStats {
  total: number;
  sent: number;
  failed: number;
  pending: number;
  skipped: number;
  byPurpose: Array<{ purpose: string; total: number; sent: number; failed: number }>;
  byCountry: Array<{ countryCode: string; total: number; sent: number; failed: number }>;
}

interface OutboundRow {
  id: string;
  countryCode: string;
  language: string;
  channel: "sms" | "push" | "ussd";
  templateKey: string;
  body: string;
  status: "pending" | "sent" | "failed" | "skipped";
  attempts: number;
  purpose: string;
  adapter: string;
  recipientPhone: string | null;
  lastError: string | null;
  createdAt: string;
  dispatchedAt: string | null;
}

/**
 * Admin / regulator-facing dashboard for the Loto messaging pipeline.
 * Shows delivery statistics broken down by purpose and country, plus a
 * paginated list of recent outbound rows so an operator can spot which
 * country / template is failing and trigger a manual retry.
 */
export default function LotoMessagingAdminPage() {
  const { t } = useTranslation();
  const { toast } = useToast();
  const [statusFilter, setStatusFilter] = useState<string>("");
  const [countryFilter, setCountryFilter] = useState<string>("");

  const statsQ = useQuery<MessagingStats>({
    queryKey: ["/api/loto/admin/messaging/stats", countryFilter],
    queryFn: async () => {
      const r = await apiRequest("GET", `/api/loto/admin/messaging/stats${countryFilter ? `?countryCode=${countryFilter}` : ""}`);
      return r.json();
    },
  });

  const messagesQ = useQuery<{ messages: OutboundRow[] }>({
    queryKey: ["/api/loto/admin/messaging/messages", statusFilter, countryFilter],
    queryFn: async () => {
      const params = new URLSearchParams();
      if (statusFilter) params.set("status", statusFilter);
      if (countryFilter) params.set("countryCode", countryFilter);
      params.set("limit", "200");
      const r = await apiRequest("GET", `/api/loto/admin/messaging/messages?${params.toString()}`);
      return r.json();
    },
  });

  const retryMut = useMutation({
    mutationFn: async (id: string) => {
      const r = await apiRequest("POST", `/api/loto/admin/messaging/messages/${id}/retry`, {});
      return r.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/loto/admin/messaging/messages"] });
      queryClient.invalidateQueries({ queryKey: ["/api/loto/admin/messaging/stats"] });
      toast({ title: t("loto.adminMessaging.retryQueued", "Retry queued") });
    },
    onError: (e: unknown) => toast({
      title: t("loto.adminMessaging.retryFailed", "Retry failed"),
      description: e instanceof Error ? e.message : String(e),
      variant: "destructive",
    }),
  });

  return (
    <div className="container mx-auto p-4 md:p-6 space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold flex items-center gap-2" data-testid="title-messaging-admin">
            <MessageCircle className="w-6 h-6 text-amber-600" />
            {t("loto.adminMessaging.title", "Loto Messaging — Delivery Dashboard")}
          </h1>
          <p className="text-sm text-muted-foreground mt-1">
            {t("loto.adminMessaging.subtitle",
              "Outbound SMS / push / USSD audit trail. Demo mode never sends a real message — every row is generated by the simulated adapter.")}
          </p>
        </div>
      </div>

      <Alert>
        <AlertTriangle className="w-4 h-4" />
        <AlertTitle>{t("loto.adminMessaging.demoTitle", "DEMO mode active")}</AlertTitle>
        <AlertDescription>
          {t("loto.adminMessaging.demoBody",
            "All outbound messages on this pilot environment are dispatched via the simulated adapter. Carriers (Africa's Talking / Twilio) are wired in but only execute when PRODUCTION_MODE=true and provider credentials are present.")}
        </AlertDescription>
      </Alert>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <StatCard label="Total" value={statsQ.data?.total ?? 0} icon={<MessageCircle />} testId="stat-total" />
        <StatCard label="Sent" value={statsQ.data?.sent ?? 0} icon={<CheckCircle2 className="text-emerald-600" />} testId="stat-sent" />
        <StatCard label="Pending" value={statsQ.data?.pending ?? 0} icon={<Clock className="text-amber-600" />} testId="stat-pending" />
        <StatCard label="Failed" value={(statsQ.data?.failed ?? 0) + (statsQ.data?.skipped ?? 0)} icon={<XCircle className="text-rose-600" />} testId="stat-failed" />
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <Card data-testid="card-by-purpose">
          <CardHeader>
            <CardTitle>{t("loto.adminMessaging.byPurpose", "Delivery by purpose (last 30d)")}</CardTitle>
          </CardHeader>
          <CardContent>
            {statsQ.isLoading ? <Skeleton className="h-32 w-full" /> : (
              <table className="w-full text-sm">
                <thead><tr className="text-left border-b">
                  <th className="py-1">Purpose</th><th className="text-right">Total</th>
                  <th className="text-right">Sent</th><th className="text-right">Failed</th>
                </tr></thead>
                <tbody>
                  {(statsQ.data?.byPurpose ?? []).map((r) => (
                    <tr key={r.purpose} className="border-b" data-testid={`row-purpose-${r.purpose}`}>
                      <td className="py-1 font-mono text-xs">{r.purpose}</td>
                      <td className="text-right">{r.total}</td>
                      <td className="text-right text-emerald-700">{r.sent}</td>
                      <td className="text-right text-rose-700">{r.failed}</td>
                    </tr>
                  ))}
                  {(!statsQ.data?.byPurpose?.length) && (
                    <tr><td colSpan={4} className="text-center text-muted-foreground py-3">No data yet</td></tr>
                  )}
                </tbody>
              </table>
            )}
          </CardContent>
        </Card>

        <Card data-testid="card-by-country">
          <CardHeader>
            <CardTitle>{t("loto.adminMessaging.byCountry", "Delivery by country")}</CardTitle>
          </CardHeader>
          <CardContent>
            {statsQ.isLoading ? <Skeleton className="h-32 w-full" /> : (
              <table className="w-full text-sm">
                <thead><tr className="text-left border-b">
                  <th className="py-1">Country</th><th className="text-right">Total</th>
                  <th className="text-right">Sent</th><th className="text-right">Failed</th>
                  <th className="text-right">Rate</th>
                </tr></thead>
                <tbody>
                  {(statsQ.data?.byCountry ?? []).map((r) => (
                    <tr key={r.countryCode} className="border-b" data-testid={`row-country-${r.countryCode}`}>
                      <td className="py-1 font-mono">{r.countryCode}</td>
                      <td className="text-right">{r.total}</td>
                      <td className="text-right text-emerald-700">{r.sent}</td>
                      <td className="text-right text-rose-700">{r.failed}</td>
                      <td className="text-right">{r.total > 0 ? `${Math.round((r.sent / r.total) * 100)}%` : "—"}</td>
                    </tr>
                  ))}
                  {(!statsQ.data?.byCountry?.length) && (
                    <tr><td colSpan={5} className="text-center text-muted-foreground py-3">No data yet</td></tr>
                  )}
                </tbody>
              </table>
            )}
          </CardContent>
        </Card>
      </div>

      <Card data-testid="card-messages">
        <CardHeader className="flex flex-row items-center justify-between">
          <div>
            <CardTitle>{t("loto.adminMessaging.recent", "Recent messages")}</CardTitle>
            <CardDescription>
              {t("loto.adminMessaging.recentBody", "Most recent 200 rows. Click 'Retry' to re-queue any failed message.")}
            </CardDescription>
          </div>
          <div className="flex gap-2">
            <select
              value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)}
              className="px-2 py-1 text-sm border rounded bg-background"
              data-testid="select-status-filter"
            >
              <option value="">All statuses</option>
              <option value="pending">Pending</option>
              <option value="sent">Sent</option>
              <option value="failed">Failed</option>
              <option value="skipped">Skipped</option>
            </select>
            <input
              placeholder="Country (e.g. CI)" value={countryFilter}
              onChange={(e) => setCountryFilter(e.target.value.toUpperCase())}
              className="px-2 py-1 text-sm border rounded bg-background w-32"
              data-testid="input-country-filter"
            />
          </div>
        </CardHeader>
        <CardContent>
          {messagesQ.isLoading ? <Skeleton className="h-64 w-full" /> : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead><tr className="text-left border-b">
                  <th className="py-2">Created</th>
                  <th>Country</th>
                  <th>Channel</th>
                  <th>Template</th>
                  <th>Recipient</th>
                  <th>Status</th>
                  <th>Attempts</th>
                  <th></th>
                </tr></thead>
                <tbody>
                  {(messagesQ.data?.messages ?? []).map((m) => (
                    <tr key={m.id} className="border-b align-top" data-testid={`row-msg-${m.id}`}>
                      <td className="py-1 whitespace-nowrap text-xs">{new Date(m.createdAt).toLocaleString()}</td>
                      <td className="font-mono text-xs">{m.countryCode}</td>
                      <td><Badge variant="outline">{m.channel}</Badge></td>
                      <td className="font-mono text-xs">{m.templateKey}</td>
                      <td className="font-mono text-xs">{m.recipientPhone ?? "—"}</td>
                      <td>
                        <Badge
                          variant={m.status === "sent" ? "default"
                            : m.status === "failed" ? "destructive"
                            : "secondary"}
                          data-testid={`badge-status-${m.id}`}
                        >
                          {m.status}
                        </Badge>
                        {m.lastError && <div className="text-xs text-rose-600 mt-1">{m.lastError}</div>}
                      </td>
                      <td className="text-center">{m.attempts}</td>
                      <td>
                        {(m.status === "failed" || m.status === "skipped") && (
                          <Button size="sm" variant="ghost"
                            onClick={() => retryMut.mutate(m.id)}
                            disabled={retryMut.isPending}
                            data-testid={`button-retry-${m.id}`}
                          >
                            <RefreshCw className="w-3.5 h-3.5 mr-1" />
                            Retry
                          </Button>
                        )}
                      </td>
                    </tr>
                  ))}
                  {(!messagesQ.data?.messages?.length) && (
                    <tr><td colSpan={8} className="text-center text-muted-foreground py-4">No messages yet</td></tr>
                  )}
                </tbody>
              </table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}

function StatCard({ label, value, icon, testId }: { label: string; value: number; icon: React.ReactNode; testId: string }) {
  return (
    <Card data-testid={testId}>
      <CardContent className="pt-6">
        <div className="flex items-center justify-between">
          <div>
            <p className="text-xs text-muted-foreground uppercase tracking-wide">{label}</p>
            <p className="text-2xl font-bold mt-1">{value.toLocaleString()}</p>
          </div>
          <div className="w-8 h-8 opacity-60">{icon}</div>
        </div>
      </CardContent>
    </Card>
  );
}
