import { useMemo, useState, type ReactNode } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { AlertTriangle, ArrowRightLeft, CheckCircle2, Clock3, Plus } from "lucide-react";
import { Link } from "wouter";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";

type ResolutionCase = { id:string; borrower_id:string; transaction_reference:string; case_type:string; channel:string; amount:string|null; currency:string|null; customer_message:string|null; status:string; resolution_notes:string|null; sla_deadline:string; first_name?:string; last_name?:string; company_name?:string };
const label = (item: ResolutionCase) => item.company_name || [item.first_name, item.last_name].filter(Boolean).join(" ") || "Borrower";
const statusLabel = (status:string) => status.replaceAll("_", " ");
const statusStyle = (status:string) => status === "confirmed_resolved" ? "default" : status === "needs_human" ? "destructive" : "secondary";

export default function TransactionResolutionPage() {
  const { toast } = useToast();
  const [open, setOpen] = useState(false);
  const { data, isLoading } = useQuery<{cases:ResolutionCase[]}>({ queryKey: ["/api/transaction-resolution-cases"] });
  const cases = data?.cases || [];
  const active = useMemo(() => cases.filter(item => !["confirmed_resolved", "rejected"].includes(item.status)), [cases]);
  const overdue = useMemo(() => active.filter(item => new Date(item.sla_deadline) < new Date()), [active]);
  const create = useMutation({ mutationFn: async (payload: Record<string, unknown>) => (await apiRequest("POST", "/api/transaction-resolution-cases", payload)).json(), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["/api/transaction-resolution-cases"] }); setOpen(false); toast({ title: "Resolution case opened" }); }, onError: (error: Error) => toast({ title: "Could not open case", description: error.message, variant: "destructive" }) });
  const update = useMutation({ mutationFn: async ({ id, status, resolutionNotes }: {id:string;status:string;resolutionNotes:string}) => (await apiRequest("PATCH", `/api/transaction-resolution-cases/${id}`, { status, resolutionNotes })).json(), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["/api/transaction-resolution-cases"] }); toast({ title: "Case updated" }); }, onError: (error: Error) => toast({ title: "Could not update case", description: error.message, variant: "destructive" }) });
  return <main className="mx-auto max-w-6xl space-y-6 p-4 md:p-8" data-testid="transaction-resolution-desk">
    <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-widest text-primary">Service recovery operations</p><h1 className="mt-2 text-3xl font-bold">Transaction Resolution Desk</h1><p className="mt-2 max-w-3xl text-muted-foreground">Triage failed transfers, double debits, cash-dispense failures, and account freezes. UCH records the decision; the bank core system remains the source of truth for any funds movement.</p></div><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Plus className="mr-2 size-4"/>Open case</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Open transaction resolution case</DialogTitle><DialogDescription>Use the bank transaction reference. The case is due for first resolution within 72 hours.</DialogDescription></DialogHeader><form className="space-y-3" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); create.mutate({ borrowerId: form.get("borrowerId"), transactionReference: form.get("reference"), caseType: form.get("caseType"), channel: form.get("channel"), amount: form.get("amount") || undefined, currency: form.get("currency") || undefined, customerMessage: form.get("message") || undefined }); }}><div><Label htmlFor="borrowerId">Borrower ID</Label><Input id="borrowerId" name="borrowerId" required placeholder="UUID from borrower record"/></div><div><Label htmlFor="reference">Transaction reference</Label><Input id="reference" name="reference" required/></div><div className="grid grid-cols-2 gap-3"><div><Label>Case type</Label><Select name="caseType" defaultValue="failed_transfer"><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="failed_transfer">Failed transfer</SelectItem><SelectItem value="double_debit">Double debit</SelectItem><SelectItem value="cash_dispense">Cash dispense</SelectItem><SelectItem value="account_freeze">Account freeze</SelectItem></SelectContent></Select></div><div><Label htmlFor="channel">Channel</Label><Input id="channel" name="channel" defaultValue="mobile"/></div></div><div className="grid grid-cols-2 gap-3"><div><Label htmlFor="amount">Amount (optional)</Label><Input id="amount" name="amount" type="number" min="0" step="0.01"/></div><div><Label htmlFor="currency">Currency</Label><Input id="currency" name="currency" maxLength={3} placeholder="GHS"/></div></div><div><Label htmlFor="message">Customer report</Label><Textarea id="message" name="message"/></div><Button type="submit" disabled={create.isPending}>{create.isPending ? "Opening…" : "Open controlled case"}</Button></form></DialogContent></Dialog></header>
    <section className="grid gap-4 md:grid-cols-3"><Metric icon={<ArrowRightLeft/>} label="Active cases" value={active.length}/><Metric icon={<AlertTriangle className="text-red-600"/>} label="Past SLA" value={overdue.length}/><Metric icon={<CheckCircle2 className="text-emerald-600"/>} label="Resolved" value={cases.filter(item => item.status === "confirmed_resolved").length}/></section>
    <Card><CardHeader><CardTitle>Resolution queue</CardTitle><CardDescription>Every decision is auditable. “Confirmed resolved” requires a recorded core-banking confirmation in the case note.</CardDescription></CardHeader><CardContent>{isLoading ? <p>Loading…</p> : cases.length ? <div className="space-y-3">{cases.map(item => <article key={item.id} className="rounded-lg border p-4"><div className="flex flex-col justify-between gap-3 md:flex-row"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{item.transaction_reference}</p><Badge variant={statusStyle(item.status)}>{statusLabel(item.status)}</Badge>{new Date(item.sla_deadline) < new Date() && !["confirmed_resolved", "rejected"].includes(item.status) ? <Badge variant="destructive">SLA overdue</Badge> : null}</div><p className="mt-1 text-sm text-muted-foreground">{item.case_type.replaceAll("_", " ")} · {item.channel} · {item.amount ? `${item.currency || ""} ${item.amount}` : "Amount not captured"}</p><p className="mt-1 text-sm">{label(item)} · <Link className="text-primary underline" href={`/borrowers/${item.borrower_id}`}>open borrower</Link></p>{item.customer_message ? <p className="mt-2 text-sm text-muted-foreground">“{item.customer_message}”</p> : null}</div><p className="flex items-center gap-1 text-sm text-muted-foreground"><Clock3 className="size-4"/>Due {new Date(item.sla_deadline).toLocaleString()}</p></div><CaseActions item={item} disabled={update.isPending} onUpdate={(status, resolutionNotes) => update.mutate({ id: item.id, status, resolutionNotes })}/></article>)}</div> : <p className="text-muted-foreground">No transaction cases in this scope.</p>}</CardContent></Card>
  </main>;
}

function Metric({ icon, label, value }: {icon:ReactNode; label:string; value:number}) { return <Card><CardContent className="flex items-center gap-3 p-5"><div className="text-primary">{icon}</div><div><p className="text-2xl font-bold">{value}</p><p className="text-sm text-muted-foreground">{label}</p></div></CardContent></Card>; }
function CaseActions({ item, onUpdate, disabled }: {item:ResolutionCase; onUpdate:(status:string, note:string)=>void; disabled:boolean}) { const [note, setNote] = useState(""); const status = item.status === "new" ? "verifying" : item.status === "verifying" ? "ready_for_core_handoff" : item.status === "ready_for_core_handoff" ? "confirmed_resolved" : "needs_human"; const action = status === "verifying" ? "Start verification" : status === "ready_for_core_handoff" ? "Send to core-banking handoff" : status === "confirmed_resolved" ? "Confirm core resolution" : "Escalate"; return <div className="mt-4 flex flex-col gap-2 border-t pt-3 sm:flex-row"><Input value={note} onChange={event => setNote(event.target.value)} placeholder="Required decision note" aria-label="Resolution note"/><Button variant="outline" disabled={disabled || note.trim().length < 3 || ["confirmed_resolved", "rejected"].includes(item.status)} onClick={() => onUpdate(status, note)}>{action}</Button></div>; }
