// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/training-center/AcademyMode.tsx": () => import("../components/mockups/training-center/AcademyMode.tsx"),
  "./components/mockups/training-center/GameMode.tsx": () => import("../components/mockups/training-center/GameMode.tsx"),
  "./components/mockups/training-center/MissionMode.tsx": () => import("../components/mockups/training-center/MissionMode.tsx")
};
